/*
 * Ejemplo6.java
 *
 * Created on 4 de mayo de 2009, 22:33
 */

package PqUd8;

import javax.swing.JOptionPane;

/**
 *
 * @author  p
 */
public class Ej8_14 extends javax.swing.JFrame {

    /** Creates new form Ejemplo6 */
    public Ej8_14() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txfEuros = new javax.swing.JTextField();
        lblEuros = new javax.swing.JLabel();
        btnConvertir = new javax.swing.JButton();
        lblPtas = new javax.swing.JLabel();
        txfPtas = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cambio moneda");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txfEuros.setColumns(10);
        txfEuros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfEuros.setText("0.0");
        txfEuros.setNextFocusableComponent(btnConvertir);

        lblEuros.setDisplayedMnemonic('E');
        lblEuros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEuros.setLabelFor(txfEuros);
        lblEuros.setText("Euros");

        btnConvertir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConvertir.setMnemonic('C');
        btnConvertir.setText("Convertir");
        btnConvertir.setToolTipText("Convierte de euros a ptas.");
        btnConvertir.setNextFocusableComponent(btnLimpiar);
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        lblPtas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPtas.setText("Ptas.");

        txfPtas.setEditable(false);
        txfPtas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfPtas.setText("0,00");
        txfPtas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfPtas.setEnabled(false);
        txfPtas.setFocusable(false);

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PqUnidad8/papelera.gif"))); // NOI18N
        btnLimpiar.setMnemonic('L');
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("Borra contenido euros y pesetas");
        btnLimpiar.setNextFocusableComponent(txfEuros);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEuros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfEuros, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPtas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfPtas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEuros)
                    .addComponent(txfEuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfPtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPtas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(btnConvertir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void borrarDatos()
{
    txfEuros.setText("0.0");
    txfPtas.setText("0,00");
}

private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
    final double CAMBIO = 166.386;
    
    double euros, ptas;
    
    euros = 0.0;
    try
    {
        euros = Double.parseDouble(txfEuros.getText());
    	ptas = (euros * CAMBIO);
    	txfPtas.setText(String.format("%.2f", ptas));
    }
    catch (NumberFormatException exc)  // capturamos error de formato
    {
        JOptionPane.showMessageDialog(this, 
                "Sólo se pueden introducir números y el punto decimal"
                ,"Error en el formato numérico",  
                JOptionPane.ERROR_MESSAGE);
        borrarDatos();
        
        txfEuros.requestFocus();
        txfEuros.selectAll();
   }


}//GEN-LAST:event_btnConvertirActionPerformed

private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    borrarDatos();
    txfEuros.requestFocus();
    txfEuros.selectAll();
}//GEN-LAST:event_btnLimpiarActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    // TODO add your handling code here:
    txfEuros.requestFocus();
    txfEuros.selectAll();
}//GEN-LAST:event_formWindowOpened




    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej8_14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEuros;
    private javax.swing.JLabel lblPtas;
    private javax.swing.JTextField txfEuros;
    private javax.swing.JTextField txfPtas;
    // End of variables declaration//GEN-END:variables

}
