/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PqUd8;

import javax.swing.JOptionPane;

/**
 *
 * @author andreu
 */
public class Ej8_22 extends javax.swing.JFrame {

    /**
     * Creates new form Ej8_22
     */
    public Ej8_22() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panBox = new javax.swing.JPanel();
        chkEncendida = new javax.swing.JCheckBox();
        btnClavija = new javax.swing.JButton();
        btnComprobar = new javax.swing.JButton();
        panButton = new javax.swing.JPanel();
        btnRojo = new javax.swing.JButton();
        btnAmarillo = new javax.swing.JButton();
        btnVerde = new javax.swing.JButton();
        btnProbar = new javax.swing.JButton();
        rdbRojo = new javax.swing.JRadioButton();
        rdbAmarillo = new javax.swing.JRadioButton();
        rdbVerde = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panBox.setBorder(javax.swing.BorderFactory.createTitledBorder("CheckBox"));

        chkEncendida.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        chkEncendida.setMnemonic('E');
        chkEncendida.setText("Encendida");

        btnClavija.setText("Clavija");
        btnClavija.setNextFocusableComponent(btnComprobar);
        btnClavija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClavijaActionPerformed(evt);
            }
        });

        btnComprobar.setText("Comprobar");
        btnComprobar.setNextFocusableComponent(btnRojo);
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBoxLayout = new javax.swing.GroupLayout(panBox);
        panBox.setLayout(panBoxLayout);
        panBoxLayout.setHorizontalGroup(
            panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBoxLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(chkEncendida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBoxLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClavija, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprobar))
                .addGap(16, 16, 16))
        );
        panBoxLayout.setVerticalGroup(
            panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBoxLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(chkEncendida)
                .addGap(52, 52, 52)
                .addComponent(btnClavija)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprobar)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        panButton.setBorder(javax.swing.BorderFactory.createTitledBorder("RadioButton"));

        btnRojo.setMnemonic('j');
        btnRojo.setText("Marca Rojo");
        btnRojo.setNextFocusableComponent(btnAmarillo);
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });

        btnAmarillo.setMnemonic('i');
        btnAmarillo.setText("Marca Amarillo");
        btnAmarillo.setNextFocusableComponent(btnVerde);
        btnAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmarilloActionPerformed(evt);
            }
        });

        btnVerde.setMnemonic('d');
        btnVerde.setText("Marca Verde");
        btnVerde.setNextFocusableComponent(btnProbar);
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });

        btnProbar.setMnemonic('P');
        btnProbar.setText("Probar");
        btnProbar.setNextFocusableComponent(btnClavija);
        btnProbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbRojo);
        rdbRojo.setMnemonic('R');
        rdbRojo.setText("Rojo");

        buttonGroup1.add(rdbAmarillo);
        rdbAmarillo.setMnemonic('A');
        rdbAmarillo.setText("Amarillo");

        buttonGroup1.add(rdbVerde);
        rdbVerde.setMnemonic('V');
        rdbVerde.setText("Verde");

        javax.swing.GroupLayout panButtonLayout = new javax.swing.GroupLayout(panButton);
        panButton.setLayout(panButtonLayout);
        panButtonLayout.setHorizontalGroup(
            panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonLayout.createSequentialGroup()
                .addGroup(panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panButtonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbRojo)
                            .addComponent(rdbAmarillo)
                            .addComponent(rdbVerde))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAmarillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panButtonLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnProbar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panButtonLayout.setVerticalGroup(
            panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRojo)
                    .addComponent(rdbRojo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAmarillo)
                    .addComponent(rdbAmarillo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerde)
                    .addComponent(rdbVerde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnProbar)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClavijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClavijaActionPerformed
        if(!chkEncendida.isSelected())
        {
            chkEncendida.setSelected(true);
        }
        else
        {
            chkEncendida.setSelected(false);
        }
        
    }//GEN-LAST:event_btnClavijaActionPerformed

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        String opcion;
        if(chkEncendida.isSelected())
        {
            opcion = "Encendida";
        }
        else
        {
            opcion = "Apagada";
        }
        
        JOptionPane.showMessageDialog(this, opcion, "Datos de pantalla", JOptionPane.INFORMATION_MESSAGE);  
    }//GEN-LAST:event_btnComprobarActionPerformed

    private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed
        rdbRojo.setSelected(true);
    }//GEN-LAST:event_btnRojoActionPerformed

    private void btnAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmarilloActionPerformed
        rdbAmarillo.setSelected(true);
    }//GEN-LAST:event_btnAmarilloActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        rdbVerde.setSelected(true);
    }//GEN-LAST:event_btnVerdeActionPerformed

    private void btnProbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarActionPerformed
        String opcion;
        opcion = "";
        
        if(rdbRojo.isSelected())
        {
            opcion = "Rojo";
        }
        
        if(rdbAmarillo.isSelected())
        {
            opcion = "Amarillo";
        }
        
        if(rdbVerde.isSelected())
        {
            opcion = "Verde";
        }
        
        JOptionPane.showMessageDialog(this, "" + opcion, "Datos de pantalla", JOptionPane.INFORMATION_MESSAGE);  
    }//GEN-LAST:event_btnProbarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        rootPane.setDefaultButton(btnProbar);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej8_22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej8_22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej8_22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej8_22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej8_22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmarillo;
    private javax.swing.JButton btnClavija;
    private javax.swing.JButton btnComprobar;
    private javax.swing.JButton btnProbar;
    private javax.swing.JButton btnRojo;
    private javax.swing.JButton btnVerde;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkEncendida;
    private javax.swing.JPanel panBox;
    private javax.swing.JPanel panButton;
    private javax.swing.JRadioButton rdbAmarillo;
    private javax.swing.JRadioButton rdbRojo;
    private javax.swing.JRadioButton rdbVerde;
    // End of variables declaration//GEN-END:variables
}
