/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PqUd8;

/**
 *
 * @author usuario
 */
public class Ej8_12A extends javax.swing.JFrame {

    /**
     * Creates new form Ej8_12A
     */
    public Ej8_12A() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDireccion = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        lblDireccion1 = new javax.swing.JLabel();
        txfNCaract = new javax.swing.JTextField();
        btnGraba = new javax.swing.JButton();
        btnPruebas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graba dirección");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblDireccion.setDisplayedMnemonic('D');
        lblDireccion.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblDireccion.setLabelFor(txfDireccion);
        lblDireccion.setText("Dirección :");

        txfDireccion.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txfDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txfDireccion.setText("C/");
        txfDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfDireccionFocusLost(evt);
            }
        });

        lblDireccion1.setDisplayedMnemonic('N');
        lblDireccion1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblDireccion1.setLabelFor(txfNCaract);
        lblDireccion1.setText("Nº Caract :");

        txfNCaract.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txfNCaract.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfNCaract.setText("2");
        txfNCaract.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfNCaractFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfNCaractFocusLost(evt);
            }
        });

        btnGraba.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnGraba.setMnemonic('G');
        btnGraba.setText("Graba");
        btnGraba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabaActionPerformed(evt);
            }
        });

        btnPruebas.setText("Pruebas");
        btnPruebas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGraba)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDireccion)
                                    .addGap(31, 31, 31)
                                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDireccion1)
                                    .addGap(31, 31, 31)
                                    .addComponent(txfNCaract, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPruebas)
                        .addGap(229, 229, 229))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion1)
                    .addComponent(txfNCaract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGraba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnPruebas)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfDireccionFocusGained
        // TODO add your handling code here:
        txfDireccion.selectAll();
    }//GEN-LAST:event_txfDireccionFocusGained

    private void txfNCaractFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNCaractFocusGained
        // TODO add your handling code here:
        txfNCaract.selectAll();
    }//GEN-LAST:event_txfNCaractFocusGained

    private void txfNCaractFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNCaractFocusLost
        // TODO add your handling code here:
        txfNCaract.select(-1,-1);

    }//GEN-LAST:event_txfNCaractFocusLost

    private void txfDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfDireccionFocusLost
        // TODO add your handling code here:
        txfDireccion.select(-1,-1);

    }//GEN-LAST:event_txfDireccionFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txfDireccion.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    
    private boolean contieneNegro(String pCad)
    {
        //Comprueba que la cadena que se le pasa como parámetro contiene 
        //AL MENOS un carácter distinto de blanco
        boolean conNegro;
        int k;
        
        //Si la cadena quitándole blancops en los extremos NO está vacía
        if(pCad.trim().isEmpty()) //Es que contiene UN NEGRO(no blanco) como mínimo
        {
            conNegro = false;
        }//FIN Si la cadena no está vacía
        else
        {
            conNegro = true; //Partimos de que no contiene ningún carácter distinto de blanco
        }
        
        //se podría haber hecho conNegro = (pCad.trim().length() != 0)
        return conNegro;
    } //FIN  contieneNegro()       

    
    
    private void btnGrabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabaActionPerformed
        boolean todoValido;
        String direcCad,nCaractCad;
        int numCaracInt;

        Direccion direc1;
        
        numCaracInt = 0;
        todoValido = true;

        //---------------------Dirección---------------------
        direcCad = ((txfDireccion.getText()).trim());
        // Si no está informado (campo obligatorio)
        if ((todoValido== true) &&  (contieneNegro(direcCad)== false) )
        {
            todoValido = false;
            System.out.println("¡ERROR. Dirección vacía!");
            txfDireccion.requestFocus(); // Enviamos foco a campo erróneo
        }
        
       
        
        //---------------------NumCaract---------------------
        nCaractCad = ((txfNCaract.getText()).trim());
        // Si todo ha ido bien y NºCaract está informado (OJO: NCaract puede no estar informado!!!
        if ((todoValido== true) && (nCaractCad.length() != 0))
        {
            // transformo a entero
            numCaracInt = Integer.parseInt(nCaractCad);
            
            // Si la longitud de Dirección NO coincide con el valor de Nª Caract
            if (direcCad.length() != numCaracInt)
            {
                todoValido = false;
                System.out.println("¡ERROR. Nº Caract. erróneo!");
                txfNCaract.requestFocus(); // Enviamos foco a campo erróneo
            }
         } // FIN Si todo ha ido bien y NºCaract está informado
        
        
        
         if (todoValido == true) // Si todo ha ido bien(validaciones correctas)
         {
             //Creamos objeto Direccion
             direc1 = new Direccion(direcCad, numCaracInt);

         } //FIN Si todo ha ido bien(validaciones correctas)    
             
        //FIN btnGrabaActionPerformed
    }//GEN-LAST:event_btnGrabaActionPerformed

    private void btnPruebasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebasActionPerformed
        // TODO add your handling code here:
        System.out.println( contieneNegro(""));
        System.out.println( contieneNegro("    "));
        System.out.println( contieneNegro("  b  "));
        System.out.println( contieneNegro("  2  "));
        System.out.println( contieneNegro("  ª  "));
    }//GEN-LAST:event_btnPruebasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej8_12A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej8_12A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej8_12A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej8_12A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej8_12A().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraba;
    private javax.swing.JButton btnPruebas;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccion1;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfNCaract;
    // End of variables declaration//GEN-END:variables
}
