/*
 * Ejemplo6.java
 *
 * Created on 4 de mayo de 2009, 22:33
 */

package PqUd8;

/**
 *
 * @author  p
 */
public class Ej8_7 extends javax.swing.JFrame {

    void hola()
    {
        System.out.println("Hola");
    }
  
    
    /** Creates new form Ejemplo6 */
    public Ej8_7() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txfAltura = new javax.swing.JTextField();
        txfPeso = new javax.swing.JTextField();
        lblAltura = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        btnCalculaIMC = new javax.swing.JButton();
        lblIMC = new javax.swing.JLabel();
        txfIMC = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Índice de Masa Corporal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txfAltura.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txfAltura.setText("0.0");
        txfAltura.setNextFocusableComponent(txfPeso);
        txfAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfAlturaFocusGained(evt);
            }
        });
        txfAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfAlturaActionPerformed(evt);
            }
        });

        txfPeso.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txfPeso.setText("0");
        txfPeso.setNextFocusableComponent(btnCalculaIMC);
        txfPeso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfPesoFocusGained(evt);
            }
        });

        lblAltura.setDisplayedMnemonic('A');
        lblAltura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAltura.setLabelFor(txfAltura);
        lblAltura.setText("Altura (mts) ");

        lblPeso.setDisplayedMnemonic('P');
        lblPeso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPeso.setLabelFor(txfPeso);
        lblPeso.setText("Peso (kg)");

        btnCalculaIMC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculaIMC.setMnemonic('C');
        btnCalculaIMC.setText("Calcular IMC");
        btnCalculaIMC.setNextFocusableComponent(txfAltura);
        btnCalculaIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaIMCActionPerformed(evt);
            }
        });

        lblIMC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIMC.setText("Índice Masa Corporal");

        txfIMC.setEditable(false);
        txfIMC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfIMC.setText("0,0");
        txfIMC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfIMC.setEnabled(false);
        txfIMC.setFocusable(false);
        txfIMC.setNextFocusableComponent(txfAltura);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblAltura)
                .addGap(1, 1, 1)
                .addComponent(txfAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(lblPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnCalculaIMC)
                .addGap(13, 13, 13)
                .addComponent(lblIMC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPeso)
                        .addComponent(txfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAltura)
                        .addComponent(txfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculaIMC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIMC)
                            .addComponent(txfIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCalculaIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaIMCActionPerformed
    double altura, imc;
    int peso;
    String imcCad;
    
    peso = Integer.parseInt(txfPeso.getText());
    altura = Double.parseDouble(txfAltura.getText());
    imc = (peso/(altura * altura)); //Math.pow()

    imcCad = String.format("%.2f", imc);
    txfIMC.setText(imcCad);
    
   // txfAltura.requestFocus();
    
  //  hola();

    
}//GEN-LAST:event_btnCalculaIMCActionPerformed

private void txfAlturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfAlturaFocusGained
    // TODO add your handling code here:
    txfAltura.selectAll();
}//GEN-LAST:event_txfAlturaFocusGained

private void txfPesoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfPesoFocusGained
    // TODO add your handling code here:
    txfPeso.selectAll();
}//GEN-LAST:event_txfPesoFocusGained

    private void txfAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfAlturaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txfAltura.requestFocus();
        //rootPane.setDefaultButton(btnCalculaIMC);
    }//GEN-LAST:event_formWindowOpened

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej8_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculaIMC;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JTextField txfAltura;
    private javax.swing.JTextField txfIMC;
    private javax.swing.JTextField txfPeso;
    // End of variables declaration//GEN-END:variables

}
