/*
 * Ej10_18.java
 *
 * Created on 28 de mayo de 2009, 23:51
 */

package PqUd8;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author  p
 */




public class Ej8_21 extends javax.swing.JFrame {

    /** Creates new form Ej10_18 */
    public Ej8_21() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatos = new javax.swing.JPanel();
        lblNotas = new javax.swing.JLabel();
        txfNota1 = new javax.swing.JTextField();
        txfNota2 = new javax.swing.JTextField();
        txfNota3 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alumnos DAI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        panDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Datos ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 0, 0))); // NOI18N
        panDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panDatosKeyPressed(evt);
            }
        });

        lblNotas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNotas.setText("Notas");

        txfNota1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfNota1.setText("0");
        txfNota1.setNextFocusableComponent(txfNota2);
        txfNota1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfNota1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfNota1FocusLost(evt);
            }
        });

        txfNota2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfNota2.setText("0");
        txfNota2.setNextFocusableComponent(txfNota3);
        txfNota2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfNota2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfNota2FocusLost(evt);
            }
        });

        txfNota3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfNota3.setText("0");
        txfNota3.setNextFocusableComponent(btnGuardar);
        txfNota3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfNota3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfNota3FocusLost(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setMnemonic('G');
        btnGuardar.setText("Guardar");
        btnGuardar.setNextFocusableComponent(btnSalir);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setMnemonic('S');
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDatosLayout = new javax.swing.GroupLayout(panDatos);
        panDatos.setLayout(panDatosLayout);
        panDatosLayout.setHorizontalGroup(
            panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addGroup(panDatosLayout.createSequentialGroup()
                        .addComponent(lblNotas)
                        .addGap(18, 18, 18)
                        .addComponent(txfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosLayout.createSequentialGroup()
                        .addComponent(txfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panDatosLayout.setVerticalGroup(
            panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotas)
                    .addComponent(txfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private double notaMedia(int [] pArNotas)
{
    //Devuelve la nota media obtenida como la media de los valores que aparecen en el array notas
    //Lo declaramos static para no crear objeto Alumno a la hora de llamarlo

    double media,suma;
    int k;
    suma = 0;

    for (k = 0; k<= pArNotas.length-1; k = k+1)
    {
        suma = suma + pArNotas[k];
    }

    media = (suma/pArNotas.length);

    return media;
}

private boolean todoDigitos (String cadena)
{
    // Se podría hacer con excepciones: capturando la excepcion NumberFormatException
    // que saltaría si la cadena existente al hacer ParseInt no representa un nº
    // PEROOOOOO si utilizamos más de 11 digitos la excepción salta porque un integer
    // no soporta ese nº tan grande.
    
    //Devuelve verdadero si todos los caracteres de la cadena son dígitos.
    //Se considera la cadena sin espacios en los laterales.
    //Se comprueba que no está vacía(se devuelve falso en ese caso)
    boolean todoDigitos;
    int k;
 
    todoDigitos = true;
    
   // cadena = cadena.trim();
       
    // Si cadena está informada 
    if (cadena.length() !=0 )
    {
        //Recorremos el contenido de cadena
        k = 0;
        while (  (k<= cadena.length()-1) &&  (todoDigitos == true))
        {
            // Si NO es dígito
            if (!(Character.isDigit(cadena.charAt(k))))
            {
                todoDigitos = false;
            }
            
            k = k+1;
        }//FIN Recorremos el contenido de cadena
        
    }    
    else // Si cadena NO está informada 
    {
        todoDigitos = false;
    }
    
    return todoDigitos;
}

    

private boolean validaNota(JTextField pTxfNota)
//Se le podría pasar el String pero a partir d ahora se da como materia 
//El pasar objetos de la ventana        
{// ----------- Valida el campo Nota
    
    // HAced tod Apara cada nota
    //haced comprueba nota para cad notaz
    boolean continua;
    int notaInt;
    String pNotaStr;
    
    continua = true;
    notaInt = 0;
    pNotaStr = pTxfNota.getText().trim(); 
     
    
    // Si nota está informada
    if (pNotaStr.length() != 0)
    {

        // Si NO son todo dígitos
        if (todoDigitos(pNotaStr) == false)
        {
            continua = false;
            JOptionPane.showMessageDialog(this, 
                    "Deben ser todos dígitos",
                    "Error en Nota",  JOptionPane.ERROR_MESSAGE);
        }// FIN Si NO son todo dígitos
        else // Si todo son dígitos
        {
            // transformo a entero
            notaInt = Integer.parseInt(pNotaStr);
        } // FIN Si todo son dígitos

        
        
        // Si la nota no está entre 0 y 10
        if ((continua == true) 
                && ((notaInt <0) || (notaInt>10)))
        {
            continua = false;
            JOptionPane.showMessageDialog(this, 
                    "Debe estar entre 0 y 10",
                    "Error en Nota",  JOptionPane.ERROR_MESSAGE);
        } // FIN Si la nota NO está entre 0 y 10

        if ((continua == false)) //Si hubo eror
        {
            pTxfNota.requestFocus(); //Asignamos foco a campo erróneo
        } // FIN Si la nota NO está entre 0 y 10

    }//Fin  Si nota está informada
    else
    {
        pTxfNota.setText("0"); //se informa a 0 si no está informada
        pTxfNota.requestFocus();
             
    }


    return continua;
}// FIN validanota()



private void guardaDatos()
{
    String  datos, strMedia;
    int nota1, nota2, nota3, intMedia;
    double media;
    
    nota1 = Integer.parseInt(txfNota1.getText().trim());
    nota2 = Integer.parseInt(txfNota2.getText().trim());
    nota3 = Integer.parseInt(txfNota3.getText().trim());


    //ALUMNO-----------------------------
    int arNotas[]  ={nota1, nota2, nota3};
    media = notaMedia(arNotas);
    
    Alumno8_21 alum;
    alum = new Alumno8_21(nota1, nota2, nota3, media);
    
    datos = "";
    datos = datos + "Nota1: "+ nota1 +" \n";
    datos = datos + "Nota2: "+ nota2 +" \n";
    datos = datos + "Nota3: "+ nota3 +" \n";
    strMedia = String.format("%3.1f", media );  //NO LO PIEDE pero repasamos.
                                                //Utilizamos string para poder
                                                // formatear la media: ponemos 3
                                                // digitos(2 enteros y 1 decimal)
                                                // ya que no se puede superar con notas de 0 a 10


    datos = datos + "Nota Media: "+ strMedia +" \n";
    
    //MOstramos los datos
    JOptionPane.showMessageDialog(this, datos, 
            "Datos almacenados",
            JOptionPane.INFORMATION_MESSAGE);

} // FIN guardaDatos()


    
private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    // Si todo ha ido correcto visualizamos los datos//GEN-LAST:event_btnGuardarActionPerformed
    if ( (validaNota(txfNota1)) && (validaNota(txfNota2)) && 
            (validaNota(txfNota3)))
    {            
        guardaDatos();
    }
 }

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    // Botón por defecto Guardar://GEN-LAST:event_formWindowOpened
   rootPane.setDefaultButton(btnGuardar);
   txfNota1.requestFocus();

}

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    System.exit(0);//GEN-LAST:event_btnSalirActionPerformed
}

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
   

    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
             // TODO add your handling code here:
     
    }//GEN-LAST:event_formKeyTyped

    private void panDatosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panDatosKeyPressed
        // TODO add your handling code here:
             // TODO add your handling code here:
     
    }//GEN-LAST:event_panDatosKeyPressed

    private void txfNota1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNota1FocusGained
        // TODO add your handling code here:
        txfNota1.selectAll();
    }//GEN-LAST:event_txfNota1FocusGained

    private void txfNota2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNota2FocusGained
        // TODO add your handling code here:
        txfNota2.selectAll();

    }//GEN-LAST:event_txfNota2FocusGained

    private void txfNota3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNota3FocusGained
        // TODO add your handling code here:
        txfNota3.selectAll();

    }//GEN-LAST:event_txfNota3FocusGained

    private void txfNota1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNota1FocusLost
        // TODO add your handling code here:
        txfNota1.select(0, 0);
    }//GEN-LAST:event_txfNota1FocusLost

    private void txfNota2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNota2FocusLost
        // TODO add your handling code here:
        txfNota2.select(0, 0);

    }//GEN-LAST:event_txfNota2FocusLost

    private void txfNota3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNota3FocusLost
        // TODO add your handling code here:
        txfNota3.select(0, 0);

    }//GEN-LAST:event_txfNota3FocusLost

 

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej8_21().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JPanel panDatos;
    private javax.swing.JTextField txfNota1;
    private javax.swing.JTextField txfNota2;
    private javax.swing.JTextField txfNota3;
    // End of variables declaration//GEN-END:variables

}
