/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PqUd8;

/**
 *
 * @author andreu
 */
public class Ej8_12 extends javax.swing.JFrame {

    /**
     * Creates new form Ej8_12
     */
    public Ej8_12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrimero = new javax.swing.JLabel();
        txfPrimero = new javax.swing.JTextField();
        lblSegundo = new javax.swing.JLabel();
        txfSegundo = new javax.swing.JTextField();
        lblTercero = new javax.swing.JLabel();
        txfTercero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaComanda = new javax.swing.JTextArea();
        btnMarchando = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccionamos Menú");

        lblPrimero.setDisplayedMnemonic('P');
        lblPrimero.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblPrimero.setLabelFor(txfPrimero);
        lblPrimero.setText("Primero: ");
        lblPrimero.setToolTipText("");

        txfPrimero.setToolTipText("");
        txfPrimero.setNextFocusableComponent(txfSegundo);

        lblSegundo.setDisplayedMnemonic('S');
        lblSegundo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblSegundo.setLabelFor(lblSegundo);
        lblSegundo.setText("Segundo:");
        lblSegundo.setToolTipText("");

        txfSegundo.setNextFocusableComponent(txfTercero);

        lblTercero.setDisplayedMnemonic('T');
        lblTercero.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblTercero.setLabelFor(txfTercero);
        lblTercero.setText("Tercero:");
        lblTercero.setToolTipText("");

        txfTercero.setNextFocusableComponent(btnMarchando);

        txaComanda.setEditable(false);
        txaComanda.setColumns(20);
        txaComanda.setLineWrap(true);
        txaComanda.setRows(5);
        txaComanda.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaComanda);

        btnMarchando.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnMarchando.setMnemonic('M');
        btnMarchando.setText("Marchando");
        btnMarchando.setToolTipText("Muestra Menu");
        btnMarchando.setNextFocusableComponent(txfPrimero);
        btnMarchando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarchandoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMarchando, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTercero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSegundo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrimero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrimero)
                            .addComponent(txfPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSegundo)
                            .addComponent(txfSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTercero)
                            .addComponent(txfTercero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMarchando)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarchandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarchandoActionPerformed
        txaComanda.setText("");
        txaComanda.setText("Marchando " + txfPrimero.getText().trim() + ", " + txfSegundo.getText().trim() + " y "
            + txfTercero.getText().trim());
        
        txfPrimero.requestFocus();
    }//GEN-LAST:event_btnMarchandoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej8_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej8_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej8_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej8_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej8_12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarchando;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrimero;
    private javax.swing.JLabel lblSegundo;
    private javax.swing.JLabel lblTercero;
    private javax.swing.JTextArea txaComanda;
    private javax.swing.JTextField txfPrimero;
    private javax.swing.JTextField txfSegundo;
    private javax.swing.JTextField txfTercero;
    // End of variables declaration//GEN-END:variables
}
