/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PqUd8;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author recatala
 */
public class PruDialogos extends javax.swing.JFrame {

    /**
     * Creates new form PruDialogos
     */
    public PruDialogos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLanzaMessage = new javax.swing.JButton();
        btnLanzaOption = new javax.swing.JButton();
        btnLanzaOptionPers = new javax.swing.JButton();
        btnLanzaInput = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLanzaMessage.setText("Lanza Message");
        btnLanzaMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzaMessageActionPerformed(evt);
            }
        });

        btnLanzaOption.setText("Lanza Option");
        btnLanzaOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzaOptionActionPerformed(evt);
            }
        });

        btnLanzaOptionPers.setText("Lanza Option Personalizado");
        btnLanzaOptionPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzaOptionPersActionPerformed(evt);
            }
        });

        btnLanzaInput.setText("Lanza Input");
        btnLanzaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzaInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLanzaInput)
                    .addComponent(btnLanzaOptionPers)
                    .addComponent(btnLanzaOption)
                    .addComponent(btnLanzaMessage))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnLanzaMessage)
                .addGap(57, 57, 57)
                .addComponent(btnLanzaOption)
                .addGap(18, 18, 18)
                .addComponent(btnLanzaInput)
                .addGap(26, 26, 26)
                .addComponent(btnLanzaOptionPers)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanzaMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzaMessageActionPerformed
        // TODO add your handling code here:
        ImageIcon icono;
        icono = new ImageIcon("/Users/andreu/Documents/NetBeans/PyUd8/src/PqUd8/papelera.gif");
        
        JOptionPane.showMessageDialog(this, "Se están borrando los archivos temporales",
                "Escaneo", JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_btnLanzaMessageActionPerformed

    private void btnLanzaOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzaOptionActionPerformed
        // TODO add your handling code here:
        
        int resp;
        ImageIcon icono;
        icono = new ImageIcon("/Users/andreu/Documents/NetBeans/PyUd8/src/PqUd8/papelera.gif");
        
        resp = JOptionPane.showOptionDialog(this, "¿Desea guardar los cambios?",
                "Salir de la aplicación", JOptionPane.YES_NO_CANCEL_OPTION, 
                JOptionPane.PLAIN_MESSAGE, icono, null, null);
        
        
        
        if(resp == JOptionPane.YES_OPTION)
        {        
            JOptionPane.showMessageDialog(this, "Elegiste Sí",
                "Respuesta", JOptionPane.INFORMATION_MESSAGE);
        }
        else //NO o CANCEL OPTION
        {
            if(resp == JOptionPane.NO_OPTION)
            {        
                JOptionPane.showMessageDialog(this, "Elegiste NO",
                    "Respuesta", JOptionPane.INFORMATION_MESSAGE);
            }
            else  //CANCEL
            {
                JOptionPane.showMessageDialog(this, "Elegiste Cancel",
                    "Respuesta", JOptionPane.INFORMATION_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnLanzaOptionActionPerformed

    private void btnLanzaOptionPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzaOptionPersActionPerformed
        // TODO add your handling code here:
        int resp;
        ImageIcon icono;
        icono = new ImageIcon("/Users/andreu/Documents/NetBeans/PyUd8/src/PqUd8/papelera.gif");
        
        String[] arOpciones  = {"Claro", "Va a ser que no",  "No sabe, no contesta"};
        
        
        
        resp = JOptionPane.showOptionDialog(this, "¿Desea guardar los cambios?",
                "Salir de la aplicación", JOptionPane.YES_NO_CANCEL_OPTION, 
                JOptionPane.PLAIN_MESSAGE, icono, arOpciones, arOpciones[2]);
        
        System.out.println(resp);
        
        JOptionPane.showMessageDialog(this, "Elegiste " + arOpciones[resp],
            "Respuesta", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnLanzaOptionPersActionPerformed
    
    private void btnLanzaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzaInputActionPerformed
        String[] arOpciones = {"<=18", "19 a 30", ">=31"};
        String resp;
        
        resp = (String) JOptionPane.showInputDialog(this, "¿Intervalo de edad?", "Encuesta", 
                JOptionPane.QUESTION_MESSAGE, null, arOpciones, arOpciones[2]);
        
        if((resp!=null) && (resp.trim().isEmpty() == false))
        {
        JOptionPane.showMessageDialog(this, "Introdujistes " + resp,
            "Respuesta", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_btnLanzaInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruDialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruDialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruDialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruDialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruDialogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanzaInput;
    private javax.swing.JButton btnLanzaMessage;
    private javax.swing.JButton btnLanzaOption;
    private javax.swing.JButton btnLanzaOptionPers;
    // End of variables declaration//GEN-END:variables
}
