/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PqUd8;

/**
 *
 * @author andreu
 */
public class PruRadio extends javax.swing.JFrame {

    /** Creates new form PruRadio */
    public PruRadio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnLanza = new javax.swing.JButton();
        rdbRojo = new javax.swing.JRadioButton();
        rdbAmarillo = new javax.swing.JRadioButton();
        rdbVerde = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLanza.setMnemonic('L');
        btnLanza.setText("Lanza");
        btnLanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbRojo);
        rdbRojo.setMnemonic('R');
        rdbRojo.setSelected(true);
        rdbRojo.setText("Rojo");
        rdbRojo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbRojoItemStateChanged(evt);
            }
        });
        rdbRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRojoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbAmarillo);
        rdbAmarillo.setMnemonic('A');
        rdbAmarillo.setText("Amarillo");
        rdbAmarillo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbAmarilloItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbVerde);
        rdbVerde.setMnemonic('V');
        rdbVerde.setText("Verde");
        rdbVerde.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbVerdeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbAmarillo)
                    .addComponent(rdbRojo)
                    .addComponent(rdbVerde)
                    .addComponent(btnLanza))
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(rdbRojo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbAmarillo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnLanza)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbRojoActionPerformed

    private void btnLanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzaActionPerformed
        //rdbAmarillo.setSelected(true);
        System.out.println(rdbRojo.isSelected());
        System.out.println(rdbAmarillo.isSelected());        
        System.out.println(rdbVerde.isSelected());
    }//GEN-LAST:event_btnLanzaActionPerformed

    private void rdbRojoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbRojoItemStateChanged
        System.out.println("Cambio Rojo");
    }//GEN-LAST:event_rdbRojoItemStateChanged

    private void rdbAmarilloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbAmarilloItemStateChanged
        System.out.println("Cambio Amarillo");        // TODO add your handling code here:
    }//GEN-LAST:event_rdbAmarilloItemStateChanged

    private void rdbVerdeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbVerdeItemStateChanged
        System.out.println("Cambio Verde");
    }//GEN-LAST:event_rdbVerdeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruRadio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanza;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rdbAmarillo;
    private javax.swing.JRadioButton rdbRojo;
    private javax.swing.JRadioButton rdbVerde;
    // End of variables declaration//GEN-END:variables

}
